version: "3"
services:
  demo-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
